#"\"  \""(used for double quotes)
# \t (used for tab space)
# \\ (used for backslash)
# \n (used for new line)
# \r (used for carriage return)
# \b (used for backspace)
# \f (used for form feed)
print("\"infotech computer education\"")
print("building no.-\t45\\6")
print("first floor, opposite bank of baroda")
print("ajmer road,kishangarh(raj)")
print("phone\t-\t9829171122")
print("website\t-\twww.infotechcomputer.in")
